- name: Install and configure Elasticsearch
  hosts: elasticsearch
  become: true
  tasks:
    - name: Update the server and install apt-transport-https package
      apt:
        name: apt-transport-https
        update_cache: yes

    - name: Update package cache and fix missing dependencies
      become: true
      apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
        force_apt_get: yes

    - name: Set JAVA_HOME Environment Variables
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/lib/jvm/java-11-openjdk-amd64/bin"

    - name: Reload environment variables
      become: true
      shell: . /etc/environment

    - name: Verify JAVA_HOME environment variable
      command: echo $JAVA_HOME

    - name: Add ElasticSearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add ElasticSearch repository
      become: true
      become_method: sudo    
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main'
        filename: elastic-8.x.list
        state: present
        update_cache: yes

    - name: Install ElasticSearch 8 on Ubuntu 20.04 LTS
      apt:
        update_cache: yes
        name: elasticsearch
        state: present

    - name: Set network.host property in Elasticsearch configuration
      become: true
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^network.host:'
        line: 'network.host: 0.0.0.0'

    - name: Start ElasticSearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Check ElasticSearch service status
      service:
        name: elasticsearch
        state: started
        enabled: yes