- name: Install and configure ElasticSearch
  hosts: elasticsearch_data_nodes
  become: true
  vars:
    elasticsearch_version: latest
    elasticsearch_heap_size: 2g
    elasticsearch_cluster_name: elasticsearch
    elasticsearch_data_dir: /var/lib/elasticsearch
  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jdk
      state: present
  - name: Import the Elasticsearch PGP Key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - name: Install the Elasticsearch debian package
    apt:
      name: elasticsearch
      state: present
      update_cache: yes
  - name: Configure ElasticSearch
    template:
      src: elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: elasticsearch
      group: elasticsearch
      mode: '0640'
  - name: Set ElasticSearch host to 0.0.0.0
    replace:
      path: /etc/elasticsearch/elasticsearch.yml
      regexp: '#network.host: 192.168.0.1'
      replace: 'network.host: {{ network_host }}'
  - name: Start and enable ElasticSearch service
    systemd:
      name: elasticsearch
      state: started
      enabled: true