- name: Install and configure Elasticsearch cluster
  hosts:
    - es01
    - es02
    - es03
  become: true
  vars:
    es01: "es01"
    es02: "es02."
    es03: "es03"
    elasticsearch_config_file: /etc/elasticsearch/elasticsearch.yml
  tasks:
    - name: Update the server and install apt-transport-https package
      apt:
        name: apt-transport-https
        update_cache: yes

    - name: Update package cache and fix missing dependencies
      become: true
      apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
        force_apt_get: yes

    - name: Set JAVA_HOME Environment Variables
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/lib/jvm/java-11-openjdk-amd64/bin"

    - name: Reload environment variables
      become: true
      shell: . /etc/environment

    - name: Verify JAVA_HOME environment variable
      command: echo $JAVA_HOME

    - name: Add ElasticSearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Add ElasticSearch repository
      become: true
      become_method: sudo
      shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Install ElasticSearch 8 on Ubuntu 20.04 LTS
      apt:
        update_cache: yes
        name: elasticsearch
        state: present

    - name: Generate Elasticsearch configuration file
      template:
        src: elasticsearch.yml.j2
        dest: "{{ elasticsearch_config_file }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
        loop:
          - "{{ es01 }}"
          - "{{ es02 }}"
          - "{{ es03 }}"
        loop_control:
          loop_var: node_name

    - name: Start Elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes

  handlers:
    - name: Restart Elasticsearch service
      service:
        name: elasticsearch
        state: restarted